keys:
  - &admin_hpcesia 56AC2ED35E51AFE66EAAA569878BD0F02991BAAE
  - &chaser_kevin age1sur93fevme8az4v6txee9uw7gk8xcpz2u0mfzvayavrcx9zkefxsmcpnln
  - &chaser_pardofelis age1l9acz0cuy455nprryeqyv6ckfqgv3tekuk0kxvvxyunsapwmpvnsmaazhy
creation_rules:
  - path_regex: ^secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin_hpcesia
        age:
          - *chaser_kevin
          - *chaser_pardofelis
  - path_regex: ^secrets/hosts/pardofelis/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin_hpcesia
        age:
          - *chaser_pardofelis
