keys:
  - &admin_hpcesia E2D9FA1509BBC65A130929A9E6EEA9E6F84CD294
  - &user_hpcesia age18778pjmwglmame3rjpq355chxue2vr97ysj70fdyygc24prwxqrsttf84g
  - &chaser_kevin age1sur93fevme8az4v6txee9uw7gk8xcpz2u0mfzvayavrcx9zkefxsmcpnln
  - &chaser_pardofelis age1l9acz0cuy455nprryeqyv6ckfqgv3tekuk0kxvvxyunsapwmpvnsmaazhy
creation_rules:
  - path_regex: ^secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin_hpcesia
        age:
          - *user_hpcesia
          - *chaser_kevin
          - *chaser_pardofelis
  - path_regex: ^secrets/hosts/pardofelis/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin_hpcesia
        age:
          - *chaser_kevin
          - *chaser_pardofelis
